advProj_WebProjectManager/Controllers/AdvProjAuditsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using advProj_BusinessObjects;
using Microsoft.AspNetCore.Authorization;

namespace advProj_WebProjectManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdvProjAuditsController : Controller
    {
        private readonly AdvProg_DatabaseContext _context;

        public AdvProjAuditsController(AdvProg_DatabaseContext context)
        {
            _context = context;
        }

        // GET: AdvProjAudits
        public async Task<IActionResult> Index()
        {
            var advProg_DatabaseContext = _context.AdvProjAudits.Include(a => a.User);
            return View(await advProg_DatabaseContext.ToListAsync());
        }

        // GET: AdvProjAudits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AdvProjAudits == null)
            {
                return NotFound();
            }

            var advProjAudit = await _context.AdvProjAudits
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.AuditId == id);
            if (advProjAudit == null)
            {
                return NotFound();
            }

            return View(advProjAudit);
        }
    }
}

advProj_WebProjectManager/Controllers/AdvProjLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using advProj_BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace advProj_WebProjectManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdvProjLogsController : Controller
    {
        private readonly AdvProg_DatabaseContext _context;

        public AdvProjLogsController(AdvProg_DatabaseContext context)
        {
            _context = context;
        }

        // GET: AdvProjLogs
        public async Task<IActionResult> Index()
        {
            var advProg_DatabaseContext = _context.AdvProjLogs.Include(a => a.User);
            return View(await advProg_DatabaseContext.ToListAsync());
        }

        // GET: AdvProjLogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AdvProjLogs == null)
            {
                return NotFound();
            }

            var advProjLog = await _context.AdvProjLogs
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.LogId == id);
            if (advProjLog == null)
            {
                return NotFound();
            }

            return View(advProjLog);
        }
    }
}

advProj_WebProjectManager/Controllers/AdvProjProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using advProj_BusinessObjects;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using advProj_WebProjectManager.Models;
using advProj_WebProjectManager.ViewModels;
using advProj_BusinessObjects.GlobalClass;

namespace advProj_WebProjectManager.Controllers
{
    [Authorize]
    public class AdvProjProjectsController : Controller
    {
        private readonly AdvProg_DatabaseContext _context;
        private readonly UserManager<AdvProg_ApplicationUser> _userManager;

        public AdvProjProjectsController(AdvProg_DatabaseContext context, UserManager<AdvProg_ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        [Authorize]
        [HttpGet]
        // index action with search function (on get)
        public async Task<IActionResult> Index(string? ProjectName, string? StatusInput, string? Member)
        {


            try
            {
                var advProg_DatabaseContext = _context.AdvProjProjects.Include(a => a.Manager).Include(a => a.Status).Include(a => a.AdvProjTasks).AsQueryable();

                // check if the user is accsesing his 
                if (Member != null)
                {
                    // filter the projects where the user is a part of (has project task in this project)
                    // seprated for ease of readability 
                    var userTaksIds = _context.AdvProjUserTasks.Where(a => a.UserId == Global.userID).Select(b => b.TaskId);
                    var projectTasksIds = _context.AdvProjTasks.Where(a => userTaksIds.Contains(a.TaskId)).Select(b => b.ProjectId);
                    advProg_DatabaseContext = advProg_DatabaseContext.Where(a => projectTasksIds.Contains(a.ProjectId));

                    //FIX
                }
                else
                {
                    // show "my projects" - projects where i manage
                    advProg_DatabaseContext = advProg_DatabaseContext.Where(f => f.ManagerId == Global.userID);
                }


                // filttering based on seach input (project name)
                if (!String.IsNullOrEmpty(ProjectName))
                {
                    advProg_DatabaseContext = advProg_DatabaseContext.Where(f => f.ProjectName.Contains(ProjectName));
                }

                // filter based on status selection
                if (!String.IsNullOrEmpty(StatusInput))
                {
                    advProg_DatabaseContext = advProg_DatabaseContext.Where(f => f.StatusId == Convert.ToInt32(StatusInput));
                }

                // view model using the search parameters 
                var projectViewModel = new ProjectIndexViewModel
                {
                    Projects = await advProg_DatabaseContext.ToListAsync(),
                    Status = _context.AdvProjPStatuses
                };

                return View(projectViewModel);
            }
            catch (Exception ex)
            {
                // creating and saving excpetion log
                LogsAudits.addLog("Web", ex.ToString(), (int)Global.userID);

                // return to home page with error 
                TempData["ErrorMsg"] = "An Error Has Occured, Please Try Again Later";
                return RedirectToAction("Index", "Home", new { area = "" });

            }
        }


        [Authorize]
        // GET: AdvProjProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {


            try
            {
                if (id == null || _context.AdvProjProjects == null)
                {
                    return NotFound();
                }

                // to check if the user is the manager or a member of this project
                var listOfManagerProjects = _context.AdvProjProjects.Where(a => a.ManagerId == Global.userID).Select(f => f.ProjectId).ToArray();

                // to retrive if the user is a member of this project
                var userTaksIds = _context.AdvProjUserTasks.Where(a => a.UserId == Global.userID).Select(b => b.TaskId);
                var projectTasksIds = _context.AdvProjTasks.Where(a => userTaksIds.Contains(a.TaskId)).Select(b => b.ProjectId);
                var listOfMemberProjects = _context.AdvProjProjects.Where(a => projectTasksIds.Contains(a.ProjectId)).Select(f => f.ProjectId).ToArray();


                if (!(Array.Exists(listOfMemberProjects, element => element == id)))
                {
                    if (!(Array.Exists(listOfManagerProjects, element => element == id)))
                    {
                        TempData["ErrorMsg"] = "You dont have accses to the selected Project";
                        return RedirectToAction("Index");
                    }
                }


                var advProjProject = await _context.AdvProjProjects
                    .Include(a => a.Manager)
                    .Include(a => a.Status)
                    .FirstOrDefaultAsync(m => m.ProjectId == id);
                if (advProjProject == null)
                {
                    return NotFound();
                }

                return View(advProjProject);
            }
            catch (Exception ex)
            {
                // creating and saving excpetion log
                LogsAudits.addLog("Web", ex.ToString(), (int)Global.userID);

                // return to home page with error 
                TempData["ErrorMsg"] = "An Error Has Occured, Please Try Again Later";
                return RedirectToAction("Index", "Home", new { area = "" });

            }
        }

        [Authorize]
        // GET: AdvProjProjects/Create
        // no validation required as create only creates a new project not related to anything and every user can create one
        public IActionResult Create()
        {


            try
            {
                ViewData["ManagerId"] = new SelectList(_context.AdvProjUsers, "UserId", "FullName");
                ViewData["StatusId"] = new SelectList(_context.AdvProjPStatuses, "StatusId", "StatusName");
                return View();
            }
            catch (Exception ex)
            {
                // creating and saving excpetion log
                LogsAudits.addLog("Web", ex.ToString(), (int)Global.userID);

                // return to home page with error 
                TempData["ErrorMsg"] = "An Error Has Occured, Please Try Again Later";
                return RedirectToAction("Index", "Home", new { area = "" });

            }
        }

        // POST: AdvProjProjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectId,ProjectName,ProjectDescription,StartDate,EndDate,FinishDate,StatusId")] AdvProjProject advProjProject)
        {



            try
            {
                // add defualt values to user (manager id) and creation time
                AdvProjProject newProject = advProjProject;
                newProject.CreateDate = DateTime.Now.Date;
                newProject.ManagerId = Global.userID;
                newProject.StatusId = 1;

                if (ModelState.IsValid)
                {
                    _context.Add(newProject);
                    await _context.SaveChangesAsync();

                    // audit - adding a new audit to the list 
                    LogsAudits.addAudit("Web", "Create", "Project", null, newProject.ToString(), newProject.ProjectId, (int)Global.userID);


                    return RedirectToAction(nameof(Index));
                }
                ViewData["ManagerId"] = new SelectList(_context.AdvProjUsers, "UserId", "UserId", newProject.ManagerId);
                ViewData["StatusId"] = new SelectList(_context.AdvProjPStatuses, "StatusId", "StatusName", newProject.StatusId);
                return View(newProject);
            }
            catch (Exception ex)
            {
                // creating and saving excpetion log
                LogsAudits.addLog("Web", ex.ToString(), (int)Global.userID);

                // return to home page with error 
                TempData["ErrorMsg"] = "An Error Has Occured, Please Try Again Later";
                return RedirectToAction("Index", "Home", new { area = "" });

            }
        }

        [Authorize]
        // GET: AdvProjProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {



            try
            {
                if (id == null || _context.AdvProjProjects == null)
                {
                    return NotFound();
                }

                // to check if the user is the manager of this project
                var listOfUserIds = _context.AdvProjProjects.Where(a => a.ManagerId == Global.userID).Select(f => f.ProjectId).ToArray();
                if (!Array.Exists(listOfUserIds, element => element == id))
                {
                    TempData["ErrorMsg"] = "You dont have accses to the selected Project";
                    return RedirectToAction(nameof(Index));
                }

                var advProjProject = await _context.AdvProjProjects.FindAsync(id);
                if (advProjProject == null)
                {
                    return NotFound();
                }
                ViewData["ManagerId"] = new SelectList(_context.AdvProjUsers, "UserId", "UserId", advProjProject.ManagerId);
                ViewData["StatusId"] = new SelectList(_context.AdvProjPStatuses, "StatusId", "StatusName", advProjProject.StatusId);
                return View(advProjProject);

advProj_WebProjectManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - advProj_WebProjectManager</title>
    <link rel="stylesheet" href="~/css/Morph.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/advProj_WebProjectManager.styles.css" asp-append-version="true" />

    <script src="https://kit.fontawesome.com/d5bcc006a2.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                @*icon clickable*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/Logo.png" alt="Main Logo" height="50">
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">


                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">Projects</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-dark" asp-controller="AdvProjProjects" asp-action="Index">My Projects</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="AdvProjProjects" asp-action="Index" asp-route-member="true">Assigned Projects</a></li>
                            </ul>
                        </li>
                        



                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" role="button" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-dark" asp-controller="AdvProjAudits" asp-action="Index">Audits</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="AdvProjLogs" asp-action="Index">Logs</a></li>
                                </ul>
                            </li>
                        }

                    </ul>


                    <partial name="_LoginPartial"></partial>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - advProj_WebProjectManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>